# Locater values for Register
url=https://flights.qedgetech.com/
ObjReg = //a[normalize-space()='Register']
ObjName = //input[@id='name']
ObjcNumber = //input[@id='contact']
ObjEmail = //input[@id='email']
objpass = (//input[last()])[5]
objGender = //select[@name='gender']
objDOB = //input[@id='popupDatepicker']
objcheckbox = //input[@id='flexCheckChecked']
objregister = //input[@name='submit']

# TestData for Register
EnterName = testing
EnterCnumber = 2356788
EnterEmail = test723d@gmail.com
EnterPass = admin46
SelectGender = Male
EnetrDob = 20-3-2000

